{% set version = "0.2.6" %}

package:
  name: standard_names
  version: {{ version }}

source:
  url: https://github.com/csdms/standard_names/archive/v{{ version }}.tar.gz
  sha256: fd3c8b57b2b41cc12dd10d9369309e65ebb12138c1c2bbfcc6edd60e8d043414

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - snbuild = standard_names.cmd.snbuild:run
    - sndump = standard_names.cmd.sndump:run
    - snscrape = standard_names.cmd.snscrape:run
    - snsql = standard_names.cmd.snsql:run
    - snvalidate = standard_names.cmd.snvalidate:run

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyyaml
    - six

test:
  requires:
    - pytest
  imports:
    - standard_names
  commands:
    - snbuild --help
    - sndump --help
    - snscrape --help
    - snsql --help
    - snvalidate --help
    - pytest --pyargs standard_names --doctest-modules -o doctest_optionflags="NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL ALLOW_UNICODE"

about:
  home: https://github.com/csdms/standard_names
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python utilities for working with CSDMS standard names.
  description: |
    The CSDMS Standard Names provide a comprehensive set of naming
    rules and patterns that are not specific to any particular modeling
    domain. They were also designed to have many other nice features
    such as parsability and natural alphabetical grouping.
  doc_url: https://standard-names.readthedocs.io
  dev_url: https://github.com/csdms/standard_names

extra:
  recipe-maintainers:
    - mcflugen
