travis:
  secure:
    BINSTAR_TOKEN: lXL/Lek3Bs+g0Rl84IhGn6BffGxfKvJS1wBnG8VlOGHyivCdBJ8B9rhWkz9dTl+WTwZqQtftwSpkmNg6CbP22ncF7Swa60v+IDNwHFvLT3blQJf/Pn2aRaueFDsinbniO83EdfSIFw3oWM2pUjWWfUuCRMle6IHbeU1KctotH7ktWUF9+cKQsZc8xzPw8f3DCMg9HnWYzteH912kfVtyoLKYECrEi6SWRLC0TvpvspsHlC6Y4EY2PIEi9qPu+kZofV/9cbyxtNQWQzGVB9X76qE0nA7N1jxwIRGRbECVn8sJ4u5c8aBPoQf5/bfZKCLPkER6WidJvYrQn/INHRP4h1zPfYm1ehFJfGSen5zz+zp226hH7FNuYvR4vSFmnlwCKGkL4VX0aNCTKQxiFQpHgTxad2/0s85VtiKXDg5iwzdGl/F4mQcb7MHeF6hoJyF7frH4FF0HyPrEQN0Ae6jrBLhqXbYZ8raTjUDfkyKcL3sxS+3B1lm0MhRQ8u+t0w6zkE57KUG5bHS4QDoEGIaKsJ/PpmA9gMU9yRmlkF7U9aKYC0tG/GVQW49pcy48D26hBp7f36qXntwsQe4+dQ7KKMj2e7ud1XnBJH4pvftTWTBoPnQlJb25gMlUEhO9kmQWMP7G4E8D+DaoahoPTeVrQeV0mhLK2ax5wyrHnpdxEo0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
